name: auto-aur-update
on:
  push: null
  schedule:
  - cron: 1 */24 * * *
  

jobs:
  # This workflow contains a single job called "build"
  UpdatePkg:
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - koreader-bin
        
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./build-aur-action
        with:
          pkgname: ${{ matrix.PKGBUILDs }}
          pkgdir: ${{ matrix.PKGBUILDs }}
          
          
      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: koreader-bin
          pkgbuild: ${{ matrix.PKGBUILDs }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
